version: "3.6"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - net-spot

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../data/postgresql:/var/lib/postgresql
    ports:
      - 15432:5432
    networks:
      - net-spot

  test:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["python", "-m", "unittest", "discover"]
    depends_on:
      - api
      - postgres
    networks:
      - net-spot

volumes:
  postgres_data:

networks:
  net-spot:
    name: net-spot
