"""

Revision ID: 9b460d60b322
Revises: 
Create Date: 2023-05-21 02:12:14.447684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b460d60b322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('image_base64', sa.Text(), nullable=True),
        sa.Column('camera_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'images', ['image_base64'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
